"""add recurring bills and recurring bill payments

Revision ID: 110bd6d5da2f
Revises: ed2d793886fb
Create Date: 2026-07-31 04:13:26.151160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '110bd6d5da2f'
down_revision: Union[str, None] = 'ed2d793886fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_bills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'biweekly', 'monthly', 'quarterly', 'yearly', 'custom', name='recurringfrequency'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('auto_create_transaction', sa.Boolean(), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_bills_user_id'), 'recurring_bills', ['user_id'], unique=False)
    op.create_table('recurring_bill_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recurring_bill_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'paid', 'overdue', 'skipped', name='recurringbillpaymentstatus'), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurring_bill_id'], ['recurring_bills.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_bill_payments_recurring_bill_id'), 'recurring_bill_payments', ['recurring_bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_bill_payments_recurring_bill_id'), table_name='recurring_bill_payments')
    op.drop_table('recurring_bill_payments')
    op.drop_index(op.f('ix_recurring_bills_user_id'), table_name='recurring_bills')
    op.drop_table('recurring_bills')
    # ### end Alembic commands ###
