"""add merchant to cashback rules

Revision ID: 30bb18050e95
Revises: 60b2bd2675ae
Create Date: 2026-08-03 19:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '30bb18050e95'
down_revision: Union[str, None] = '60b2bd2675ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashback_rules', sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_index(op.f('ix_cashback_rules_merchant'), 'cashback_rules', ['merchant'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashback_rules_merchant'), table_name='cashback_rules')
    op.drop_column('cashback_rules', 'merchant')
    # ### end Alembic commands ###
