"""add transaction created_by_user_id

Revision ID: 4ebc1f83e8fe
Revises: 661b6c0b64aa
Create Date: 2026-08-02 05:13:06.326967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '4ebc1f83e8fe'
down_revision: Union[str, None] = '661b6c0b64aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'created_by_user_id')
    # ### end Alembic commands ###
