"""add acknowledged notifications

Revision ID: 60b2bd2675ae
Revises: e0e9786c7eaf
Create Date: 2026-08-03 17:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '60b2bd2675ae'
down_revision: Union[str, None] = 'e0e9786c7eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acknowledged_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_key', name='uq_acknowledged_notification_user_key')
    )
    op.create_index(op.f('ix_acknowledged_notifications_user_id'), 'acknowledged_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_acknowledged_notifications_notification_key'), 'acknowledged_notifications', ['notification_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acknowledged_notifications_notification_key'), table_name='acknowledged_notifications')
    op.drop_index(op.f('ix_acknowledged_notifications_user_id'), table_name='acknowledged_notifications')
    op.drop_table('acknowledged_notifications')
    # ### end Alembic commands ###
