"""add cashback rules and records

Revision ID: 7241b1a664f5
Revises: 110bd6d5da2f
Create Date: 2026-07-31 04:32:13.988624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '7241b1a664f5'
down_revision: Union[str, None] = '110bd6d5da2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashback_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('cashback_rate', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_rules_payment_method_id'), 'cashback_rules', ['payment_method_id'], unique=False)
    op.create_index(op.f('ix_cashback_rules_user_id'), 'cashback_rules', ['user_id'], unique=False)
    op.create_table('cashback_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('line_item_id', sa.Uuid(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(), nullable=False),
    sa.Column('redeemed_amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('estimated', 'redeemed', name='cashbackrecordstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['line_item_id'], ['transaction_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_records_line_item_id'), 'cashback_records', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_cashback_records_transaction_id'), 'cashback_records', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_cashback_records_user_id'), 'cashback_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashback_records_user_id'), table_name='cashback_records')
    op.drop_index(op.f('ix_cashback_records_transaction_id'), table_name='cashback_records')
    op.drop_index(op.f('ix_cashback_records_line_item_id'), table_name='cashback_records')
    op.drop_table('cashback_records')
    op.drop_index(op.f('ix_cashback_rules_user_id'), table_name='cashback_rules')
    op.drop_index(op.f('ix_cashback_rules_payment_method_id'), table_name='cashback_rules')
    op.drop_table('cashback_rules')
    # ### end Alembic commands ###
