"""add net worth accounts snapshots and balances

Revision ID: 8b16468cde43
Revises: 7241b1a664f5
Create Date: 2026-08-02 03:46:12.309562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8b16468cde43'
down_revision: Union[str, None] = '7241b1a664f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('asset', 'liability', name='networthaccounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_accounts_user_id'), 'net_worth_accounts', ['user_id'], unique=False)
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(), nullable=False),
    sa.Column('net_worth', sa.Numeric(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_snapshots_user_id'), 'net_worth_snapshots', ['user_id'], unique=False)
    op.create_table('net_worth_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['net_worth_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['net_worth_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_balances_account_id'), 'net_worth_balances', ['account_id'], unique=False)
    op.create_index(op.f('ix_net_worth_balances_snapshot_id'), 'net_worth_balances', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_net_worth_balances_snapshot_id'), table_name='net_worth_balances')
    op.drop_index(op.f('ix_net_worth_balances_account_id'), table_name='net_worth_balances')
    op.drop_table('net_worth_balances')
    op.drop_index(op.f('ix_net_worth_snapshots_user_id'), table_name='net_worth_snapshots')
    op.drop_table('net_worth_snapshots')
    op.drop_index(op.f('ix_net_worth_accounts_user_id'), table_name='net_worth_accounts')
    op.drop_table('net_worth_accounts')
    # ### end Alembic commands ###
