"""add color to payment methods

Revision ID: e0e9786c7eaf
Revises: 1a68ee1ae924
Create Date: 2026-08-03 15:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e0e9786c7eaf'
down_revision: Union[str, None] = '1a68ee1ae924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'color')
    # ### end Alembic commands ###
